name: I_am_not_good_at_naming_things

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:  
  build_os_matrix:
    name: build the matrix of OS and versions
    strategy:
      matrix:
        os: [self-hosted]
        
    runs-on: ${{ matrix.os }}
    env:
      DOCKER_REPO_NAME: devops_lab2_vainer
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Analyzing the code
        run: |
          pip install pycodestyle
          pycodestyle main.py > kowalski_analysis.txt
      
      - name: create success file
        if: success()
        run: |
          "OK" > kowalski_analysis.txt
      
      - name: Upload the results of the analysis
        if: always()
        uses: actions/upload-artifact@v3.1.2
        with:
          name: analysis
          path: kowalski_analysis.txt
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
      - name: Build image
        run: docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_REPO_NAME }}:${{ github.ref_name }} -f Dockerfile .
      - name: Push image to docker
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_REPO_NAME }}:${{ github.ref_name }}
          
  send_to_telegram:
    name: send notification to telegram
    if: always()
    
    needs: build_os_matrix
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: analysis
        
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: kowalski_analysis.txt
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
